import type { Logger, FlagMetadata } from '@openfeature/core';
import { ParseError } from '@openfeature/core';
import type { Flag } from './feature-flag';
import { FeatureFlag } from './feature-flag';
import type { FlagdCoreOptions } from './options';

// Import pre-compiled validators for Workers mode
// These are generated by scripts/build-validators.js and don't use new Function()
import precompiledValidate from './generated/validators';

// Lazy-load ajv for non-Workers mode to avoid module-level compilation
// This allows the module to be imported in Workers without immediately failing
let runtimeValidate: ValidateFn | undefined;

type ValidateFn = ((data: unknown) => boolean) & { errors?: unknown[] };

type FlagConfig = {
  flags: { [key: string]: Flag };
  metadata?: FlagMetadata;
};

type FlagSet = {
  flags: Map<string, FeatureFlag>;
  metadata: FlagMetadata;
};

/**
 * Get the runtime validator (uses ajv compilation).
 * This is lazy-loaded to avoid triggering new Function() at module load time.
 * 
 * @throws {Error} If called in an environment that doesn't support dynamic code generation
 */
function getRuntimeValidator(): ValidateFn {
  if (!runtimeValidate) {
    // These imports trigger new Function() which fails in Workers
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const Ajv = require('ajv').default;
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const flagsSchema = require('../../flagd-schemas/json/flags.json');
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const targetingSchema = require('../../flagd-schemas/json/targeting.json');

    const ajv = new Ajv({ strict: false });
    runtimeValidate = ajv.addSchema(targetingSchema).compile(flagsSchema);
  }
  return runtimeValidate!;
}

const evaluatorKey = '$evaluators';
const bracketReplacer = new RegExp('^[^{]*\\{|}[^}]*$', 'g');

const errorMessages = 'invalid flagd flag configuration';

/**
 * Validate and parse flag configurations.
 * @param flagConfig The flag configuration string.
 * @param strictValidation Validates against the flag and targeting schemas.
 * @param logger The logger to be used for troubleshooting.
 * @param options Configuration options including Workers compatibility mode.
 * @returns The parsed flag configurations.
 */
export function parse(
  flagConfig: string,
  strictValidation: boolean,
  logger: Logger,
  options: FlagdCoreOptions = {},
): FlagSet {
  try {
    const transformed = transform(flagConfig);
    const parsedFlagConfig: FlagConfig = JSON.parse(transformed);

    // Use pre-compiled validators in Workers mode to avoid new Function()
    // In Node.js, use runtime ajv compilation for full schema validation
    const validate: ValidateFn = options.workers
      ? (precompiledValidate as ValidateFn)
      : getRuntimeValidator();

    const isValid = validate(parsedFlagConfig);
    if (!isValid) {
      const message = `${errorMessages}: ${JSON.stringify(validate.errors, undefined, 2)}`;
      if (strictValidation) {
        throw new ParseError(message);
      } else {
        logger.debug(message);
      }
    }
    const flagMap = new Map<string, FeatureFlag>();

    const flagSetMetadata = parsedFlagConfig.metadata ?? {};

    for (const flagsKey in parsedFlagConfig.flags) {
      const flag = parsedFlagConfig.flags[flagsKey];
      flagMap.set(
        flagsKey,
        new FeatureFlag(
          flagsKey,
          {
            ...flag,
            // Flag metadata has higher precedence than flag set metadata
            metadata: {
              ...parsedFlagConfig.metadata,
              ...flag.metadata,
            },
          },
          logger,
          options,
        ),
      );
    }

    return {
      flags: flagMap,
      metadata: flagSetMetadata,
    };
  } catch (err) {
    if (err instanceof ParseError) {
      throw err;
    }
    throw new ParseError(errorMessages, { cause: err });
  }
}

// Transform $ref references of flagd configuration
function transform(flagCfg: string): string {
  const evaluators: { [key: string]: string } = JSON.parse(flagCfg)[evaluatorKey];

  if (!evaluators) {
    return flagCfg;
  }

  let transformed = flagCfg;

  for (const key in evaluators) {
    const replacer = JSON.stringify(evaluators[key]).replaceAll(bracketReplacer, '');
    const refRegex = new RegExp('"\\$ref":(\\s)*"' + key + '"', 'g');

    transformed = transformed.replaceAll(refRegex, replacer);
  }

  return transformed;
}
